### ISSUE TITLE
Write documentation for ***EVERYTHING***

### ISSUE THREAD

**Issue by soenkehahn** [garnix-io/garn#141]
```[tasklist]
### Tasks
- [ ] https://github.com/garnix-io/garn/issues/163
- [ ] https://github.com/garnix-io/garn/issues/164
- [ ] https://github.com/garnix-io/garn/issues/165
- [ ] https://github.com/garnix-io/garn/issues/166
- [ ] https://github.com/garnix-io/garn/issues/162
```
