### ISSUE TITLE
Support macs

### ISSUE THREAD

**Issue by soenkehahn** [garnix-io/garn#150]
Currently we're not trying out `garner` on macs at all. We should make sure that you can do basic things on macs with it.

- [x] run the tests on macs locally
  - [x] `just test`
  - [x] `just check-examples`
- [ ] try it on a real mac
  - [ ] intel
  - [x] arm
```[tasklist]
### Tasks
- [ ] https://github.com/garnix-io/garn/pull/156
- [ ] https://github.com/garnix-io/garn/issues/154
- [ ] https://github.com/garnix-io/garn/issues/155
```
