### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by soenkehahn** [garnix-io/garn#326]
We're working on (some of) this in the https://github.com/garnix-io/garn/tree/ad/landing-page branch.

```[tasklist]
### Tasks
- [ ] https://github.com/garnix-io/garn/issues/327
- [x] [landing page scenarios] Make the small text not as wide as the screen
- [x] Change the font
- [x] [landing page] Right align code snippet line numbers
- [x] Landing page hero is to wide for narrower screens (e.g. mobile)
- [x] Add more prominently that it supports go, haskell and javascript. (Add it to the faq?)
- [x] [landing page hero] Add hover over for `addExecutable`
- [x] [landing page hero] Make the `Read More` Call To Action link somewhere
- [x] [landing page scenarios] Make the example sections unfold on click, maybe?
- [x] [landing page scenarios] Have the scenarios switch through left and right arrows?
- [x] [landing page scenarios] Add a link to the tutorial (maybe titled `Read more`?)
- [x] [landing page hero] Add some explanation about what `garn` is
- [x] Capitalize programming language names consistently
- [x] Add more space to the sides of the text on all non-landing page sites
- [ ] Navigation on mobile
```

**Comment by jkarni** [comment]
- [ ] LSP configuration shouldn't have been removed form getting started (even if it's also added to FAQ). 
- [ ] Mobile is completely broken
- [ ] Github checks image is cut off
- [ ] "Read more..." seems to suggest I'd be reading more about the specific issue there. Instead, it just takes me to the same Tutorial, which doesn't even necessarily *have* more about the issue
- [ ] garnix shouldn't be mentioned in a way that suggests it's the only choice
