### ISSUE TITLE
Better building of npm packages

### ISSUE THREAD

**Issue by alexdavid** [garnix-io/garn#368]
Right now `garn build someNpmProject` always outputs a `result` directory that just includes the node modules and nothing more. Ideally there would be a way to have `garn build` be more useful for an npm project.

```[tasklist]
### Tasks
- [ ] Support specifying manual build commands via an `addPackage(name, commands)`
- [ ] Support retrieving all artifacts from a project that has multiple packages
- [ ] Support specifying a single package to build on a project with `garn build project.packge`
```
