### ISSUE TITLE
Allow to interact with commands executed through `garner run ...`

### ISSUE THREAD

**Issue by soenkehahn** [garnix-io/garn#9]
Currently there's (possibly multiple) issues when running things with `garner run ...` with respect to interacting with these processes. These things should be fixed:

```[tasklist]
### Tasks
- [ ] `nixpkgs.sl` should show a train
- [ ] `nixpkgs.neovim` should allow to get a working editor
- [ ] https://github.com/garnix-io/garner/issues/13
```
